[package]
name = "relayring-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
relayring = { path = ".." }

[[bin]]
name = "stream_fuzzer"
path = "fuzz_targets/stream_fuzzer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "state_fuzzer"
path = "fuzz_targets/state_fuzzer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "recovery_fuzzer"
path = "fuzz_targets/recovery_fuzzer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "journal_fuzzer"
path = "fuzz_targets/journal_fuzzer.rs"
test = false
doc = false
bench = false
